apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/quartz-manager-test/locations/europe-west8/clusters/gke-cluster
