apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
  annotations: {}
  labels: {}
description: prod
requireApproval: true
gke:
  cluster: projects/quartz-manager-test/locations/europe-west8-a/clusters/gke-cluster
